### ISSUE TITLE
Do you mind releasing your code for the comparison to meta gradient rl?

### ISSUE THREAD

**Issue by llucid-97** [supratikp/HOOF#1]
Hi There, great work on yor paper and thanks for the code release
 I notice in your paper, you make a lot of comparisons between HOOF and meta-gradient rl (arXiv:1805.09801). I'm struggling to implement it myself to compare it to HOOF and PBT for tuning hyper parameters in soft actor critic, but and I can't find any open source implementations for it.
Do you mind sharing your code for it?

**Comment by supratikp** [comment]
I will be updating the repo in the next couple of weeks to reflect the experiments for the NeurIPS version of our paper, but if you are looking for an implementation of meta gradients as per their paper, I am afraid our code won't help you much. In the meta gradients paper they learnt gamma/lambda while in our experiments we compare HOOF vs meta-gradients for learning the learning rate, since performance is far more sensitive to it than to gamma/lambda. 

I had emailed the author a while ago, and he had said that they were planning to release the code. Your best bet would be to get in touch with them.

**Comment by llucid-97** [comment]
I'm actually much more interested in tuning learning rates, so I think your implementation would be more informative.
Thanks for the update :)
